### ISSUE TITLE
Publish on expo

### ISSUE THREAD

**Issue by SleeplessByte** [bmcmahen/roast-buddy-react-native#1]
Hi there!

`roast-buddy` is not yet taken, [it seems like](https://expo.io/search/roast-buddy). I recommend publishing to `expo` so you can claim it yours; this also makes it easy for people to try it out, without needing to `yarn install`.

If you don't want to, let me know, I'll publish it instead.

**Comment by bmcmahen** [comment]
hey! Thanks for the tip... I haven't really touched RN in 3 years so I didn't know this functionality actually existed. Pretty cool, and I will publish it. Thanks.

**Comment by bmcmahen** [comment]
it's now published here: https://expo.io/@benmcmahen/roast-buddy
